apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mysql-dados
  labels:
    type: local-mysql-dados
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /meubanco/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mysql-dados
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: leomasg/projeto-database:2.0
        args:
        - "--ignore-db-dir=lost+found"      
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        
        volumeMounts:
        - name: local-mysql-dados
          mountPath: /var/lib/mysql
      volumes:
      - name: local-mysql-dados
        persistentVolumeClaim:
          claimName: local-mysql-dados